require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ExampleExample' do
  config = use_native_modules!

  use_react_native!(path: '../../node_modules/react-native', :hermes_enabled => true)

  pod 'splash', path: '../../packages/splash'
  pod 'rn-base-native', path: '../../packages/native/rn-base-native.podspec'
  pod 'rn-base-input-filter', path: '../../packages/input-filter/rn-base-input-filter.podspec'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # you should disable the next line.
  use_flipper!()
  post_install do |installer|
    react_native_post_install(installer)
  end
end
